name: git-diff-tui
version: '1.0.1'
summary: A human friendly version of "git diff", with a terminal UI.
description: A human friendly version of "git diff", with a terminal UI.

grade: stable
confinement: strict
base: core18

apps:
  git-diff-tui:
    command: git-diff-tui

parts:
  git-diff-tui:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/git-diff-tui
    source-type: git
    source-depth: 1
    build-snaps: [cmake/latest/edge] # We need a modern cmake.
    stage-packages:
    - git
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

passthrough:
  title: git-diff-tui
  license: MIT
