name: Linux Clang

on:
  - pull_request
  - push

jobs:
  build:
    name: Linux Clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build
        run: >
          mkdir build;
          cd build;
          cmake ..
          -DCMAKE_CXX_COMPILER=clang++;
          cmake --build . --config Release;
