name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    needs: release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary: git-tui
          - os: macos-latest
            binary: git-tui
          - os: windows-latest
            binary: git-tui.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeBuildType: Release
          buildDirectory: "${{ github.workspace }}/${{ matrix.os }}"

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: "${{ github.workspace }}/${{ matrix.os }}/${{ matrix.binary }}"
          asset_name: "${{ matrix.os }}"
          asset_content_type: application/octet-stream
